### ISSUE TITLE
Improved status design

### ISSUE THREAD

**Issue by digitarald** [mozilla/platatus#109]
What works:
- mart3ll likes the dev edition gradient in the header
- mobile design works well

Improve:
- [x] People think the icons looks broken, they probably are.
  - [x] Fading out the icon with a gradient?
- [x] Focus on Firefox status, other browsers are peripheral
- [x] Bugzilla link should be closer to Firefox status and not with general links
- [x] Palette via mart3ll: http://blog.seanmartell.com/2014/09/17/mozilla-id-project-palette-explorations/

**Comment by digitarald** [comment]
martell linked me to http://blog.seanmartell.com/2014/09/17/mozilla-id-project-palette-explorations/ for new mozilla color palette – which has all the right colors that we need for status

**Comment by dbialer** [comment]
Also - white and grey no status icon is very difficult to read and not accessible to many people. Could you use colors with more contrast?

**Comment by digitarald** [comment]
@dbialer with the new color palette the contrast should be a bit improved

**Comment by rorito** [comment]
@digitarald I think we need to just show the entire icon. I've had at least 5 people tell me they think the rendering was broken because only the top part of the icon appears

**Comment by digitarald** [comment]
yes, new status design wip, should be come in as pull request tomorrow

**Comment by digitarald** [comment]
Closing for now and opening new bugs after next design revision

**Comment by digitarald** [comment]
Fixed in #180
