### ISSUE TITLE
Feature search

### ISSUE THREAD

**Issue by potch** [mozilla/platatus#129]
I propose adding an autocomplete-style site search to the top of platatus that will let users quickly find features by doing live text search. Think something like the search box on status.modern.ie or caniuse.com.

I'm planning on building it out using https://github.com/olivernn/lunr.js (which allows for fast indexing and full-text search). I can digest status.json to build the search index on page load.

Thoughts? This is a 4th-quarter deliverable for me.

**Comment by digitarald** [comment]
:+1: we have it on our roadmap and it needs to be done given the slew of features we just added

We could either add data attributes to the features and generate the index on first-search – or generate a the search index during build, lunr can serialize the tokens it generated.
