### ISSUE TITLE
Figure out future hosting within Mozilla

### ISSUE THREAD

**Issue by digitarald** [mozilla/platatus#14]
Requirements:
- HTTPS
- Pushed live by travis when pushing to gh

@zalun might be able to help here as worked a lot more with travis and hosting, maybe even within Mozilla.

**Comment by zalun** [comment]
Options are:
- stackato
- heroku
- hosted server

I think we should use stackato, or at least give it a chance.
AFAIR Heroku is troublesome with https
We can always do hosted server

**Comment by rorito** [comment]
We can put Cloudflare's Universal SSL in front of a heroku app for free
https://www.cloudflare.com/ssl

**Comment by digitarald** [comment]
@rory, we could do the same on github (as its all static).

I propose we'll
- continue on gh-pages
- leave this ticket open
- file a bug for Mozilla's sysadmin in time to address our questions. I was in that process before for other projects and it worked out great as you have an experienced sys admin :)

**Comment by digitarald** [comment]
Heroku, done :)
