### ISSUE TITLE
Canvas Media Capture is enabled by default in Firefox 43 but shown as "in development"

### ISSUE THREAD

**Issue by marco-c** [mozilla/platatus#143]

**Comment by digitarald** [comment]
43 is beta, which is why its color coded in development but with a version. We should show a nightly/dev-edition/beta icon to make it clear.

**Comment by digitarald** [comment]
Filed #143 for last comment.

**Comment by marco-c** [comment]
> 43 is beta, which is why its color coded in development but with a version. We should show a nightly/dev-edition/beta icon to make it clear.

Are we doing the same with Chrome?

**Comment by digitarald** [comment]
@brendandahl ^

**Comment by brendandahl** [comment]
I'm not sure how chrome updates there status.

**Comment by brendandahl** [comment]
Looks like chrome changes the status to "enabled by default" as soon as it's in canary.

**Comment by marco-c** [comment]
So what we're doing now isn't really "fair" to Firefox.

**Comment by digitarald** [comment]
I like the thinking. When we show the right channel icon, we can mark it shipped. In the future we could show fine-grained details for Chrome as well so only stable releases are marked shipped as well.

**Comment by phistuck** [comment]
@digitarald - by the way, https://omahaproxy.appspot.com/json provides the data you need for that.
