### ISSUE TITLE
Push API is shipped in Chrome, but there are important features missing (e.g. payloads)

### ISSUE THREAD

**Issue by marco-c** [mozilla/platatus#159]

**Comment by marco-c** [comment]
We could add a footnote once #183 is fixed.

**Comment by digitarald** [comment]
I would even make *Push API Payloads* a separate item. When we add a 2-tiered hierarchy it could be under *Push API* (like a few other things in *Service Workers* or *Fetch API*).

**Comment by marco-c** [comment]
Brendan added a footnote in #201.
