### ISSUE TITLE
More space between text in the footer

### ISSUE THREAD

**Issue by marco-c** [mozilla/platatus#173]
"Portions of the" and "View source" should be farther from each other.

![img](https://cloud.githubusercontent.com/assets/1616846/11319945/82a8fffe-9081-11e5-8052-e37ba201e259.png)

**Comment by TimAbraldes** [comment]
The two-column layout seems a little strange to me. Could 'View source' and 'Submit feedback' be part of the content in the left-hand column?

**Comment by digitarald** [comment]
Fixed in #180
