### ISSUE TITLE
Either Change "Apple Safari" To "WebKit Nightly", Or Remove It Altogether

### ISSUE THREAD

**Issue by phistuck** [mozilla/platatus#189]
See https://github.com/MicrosoftEdge/Status/pull/226#issuecomment-97672727 - the WebKit data is not representative of Safari.
Unless, @BenjaminPoulain, this has changed.

**Comment by digitarald** [comment]
The mismatch of platform/engine development vs released product is unfortunate. This is why we are linking to the source to add the necessary nuance. Is there a specific problem where this causes a mismatch between Webkit & Safari?

**Comment by phistuck** [comment]
Any "Done" entry where its status has changed closer to be after a Safari release is not released.
While no entries that you show are problematic, Benjamin did ask the Microsoft Edge platform status project not to do this. Any feature that you may add (and I hope you will) can turn out problematic and provide a misguidance, even if only until someone discovers the issue and fixes it. I just do not think it is worth it.

**Comment by digitarald** [comment]
> See MicrosoftEdge/Status#226 (comment) - the WebKit data is not representative of Safari.

I am not sure if changing the logo from Safari to Webkit Nightly will avoid much confusion as it is the same symbol with a slightly changed color theme. Other ideas?

We are also marking features shipped for Chrome (and Firefox in the future) even when they are only in a nightly channel. The `shipped` label needs to change though (`done`, `supported`, etc?) to make it unambiguous.

**Comment by phistuck** [comment]
As a start, it says "Shipped - Apple Safari" which could be a misguidance. Change that to "Shipped - WebKit Nightly" perhaps.

Regarding Chrome versions, you can take one step farther and draw current version data from https://omahaproxy.appspot.com/json which is the JSON representation of https://omahaproxy.appspot.com/ - just like you do with Firefox.

(By the way, off topic - but why are you excluding Opera? While its feature set is very close to Chrome, it might not always be aligned and chromestatus.com provides that data, I think)

**Comment by digitarald** [comment]
> (By the way, off topic - but why are you excluding Opera? While its feature set is very close to Chrome, it might not always be aligned and chromestatus.com provides that data, I think)

It wasn't included in v1 as it doesn't publish its own status page. I just recently learned though from @andreasbovens that they are jointly maintaining the data on chromestatus.

**Comment by phistuck** [comment]
I see that you changed "Shipped" to "Landed" which almost makes the omahaproxy suggestion moot. However, yes, the version is provided, but what if it is 50 when Chrome is at 47 currently? You do not even show the version, so this is confusing.

By the way, do you know why WebRTC - https://webkit.org/status/#specification-WebRTC - shows "Not planned" in your status page while it is "In development" in the WebKit status page?
How often do you synchronize with that data? I think it was there for a few days already.

**Comment by marco-c** [comment]
> However, yes, the version is provided, but what if it is 50 when Chrome is at 47 currently? You do not even show the version, so this is confusing.

Yes, there's some discussion in #143.

> By the way, do you know why WebRTC - https://webkit.org/status/#specification-WebRTC - shows "Not planned" in your status page while it is "In development" in the WebKit status page?
How often do you synchronize with that data? I think it was there for a few days already.

Currently it's automatically synchronized when we merge pull requests. We should probably synchronize it periodically (or write a script to synchronize when there's a change in the data).
