### ISSUE TITLE
Track Opera status

### ISSUE THREAD

**Issue by digitarald** [mozilla/platatus#191]
chromestatus.com is jointly maintained by Opera and has detailed shipping status for opera (see https://www.chromestatus.com/feature/6488656873259008 )

**Comment by marco-c** [comment]
Is the Opera status different than the Chrome one?

**Comment by digitarald** [comment]
Yes, https://www.chromestatus.com/features.json has `shipped_opera_android_milestone`.

Generally we have to review the quality of data we get. I already reported the incorrect data behind https://www.chromestatus.com/feature/5416033485586432 to @andreasbovens who pinged somebody at Opera (Opera doesn't have push yet).
