### ISSUE TITLE
Use "Specification" instead of "blank draft"

### ISSUE THREAD

**Issue by annevk** [mozilla/platatus#192]
The different ways of referencing various documents are mostly wrong. It seems easier to just say "Specification" there rather than try to correct them all and keep them up to date.

**Comment by digitarald** [comment]
@annevk @overholt just to gauge importance of this aspect, would specification level give any indication on stability/adoption/readiness for a web platform feature?

**Comment by overholt** [comment]
Sometimes but not always. And I suspect @annevk would say "no" :)

https://twitter.com/tolfsen/status/614591724665442304
