### ISSUE TITLE
Badly squashed text on feature list

### ISSUE THREAD

**Issue by potch** [mozilla/platatus#217]
![screen shot 2015-12-04 at 11 20 46](https://cloud.githubusercontent.com/assets/253470/11598862/2ec8b42c-9a79-11e5-8cc7-f65de5e2e1c0.png)

**Comment by potch** [comment]
The text is unnecessarily squashed when the status isn't hovered.

**Comment by darkwing** [comment]
I was just about to file this as well;  I think we can implement the hard width/ellipses only when the row is in active state.

**Comment by brendandahl** [comment]
I mentioned this to @digitarald the other day, and I think he is working on it.

**Comment by potch** [comment]
Looks like a side effect of the way the status `ul` is constructed. It has an large intrinsic width that is being counteracted by using `transform` on the individual statuses.

An alternative approach could be to use position: absolute to have all the status `li`s be stacked and then fan them out using transforms, instead of having them all side by side and having them stack using transforms. That would make the intrinsic width of the UL only as large as a single `li`

Currently (before transforms):
```
[ Chrome  ][ Opera   ][ Safari  ][ IE       ][ Firefox ]
```
Currently (after transforms):
```
[ Ch[ Op[ Sa[ IE[ Firefox ]
```

Suggested Change (before transforms):
```
[ Firefox ] (the rest are stacked under it)
```
Suggested Change (after transforms):
```
[ Ch[ Op[ Sa[ IE[ Firefox ] (looks the same as now)
```

The hover state will look the same.

**Comment by digitarald** [comment]
The simple fix I imagined was just removing the flex and aligning the status sliders with absolute position to not affect layout. Maybe we also find a way for smaller labels as the text is imo important for understanding. Just shrinking text for other browsers would work for this.

@potch just to make sure I get this right, you suggest not showing labels even when they are unfolded?

**Comment by digitarald** [comment]
Fixed for now with absolute position.
