### ISSUE TITLE
Fix problems with HTML Imports

### ISSUE THREAD

**Issue by marco-c** [mozilla/platatus#237]
We talked about this at Orlando, but I don't recall what was the cause.

@brendandahl @digitarald

**Comment by brendandahl** [comment]
The status is correct. Harald and I talked about adding note one why it isn't planned as it's hard to tell from the bug, since it is resolved.

**Comment by digitarald** [comment]
Status is correct, the only red field for Firefox. Would be good to have a footnote here (#201?)
