### ISSUE TITLE
Track W3C Manifest implementation

### ISSUE THREAD

**Issue by wfwalker** [mozilla/platatus#24]
we should somehow track the progress of this metabug?
https://bugzilla.mozilla.org/show_bug.cgi?id=1168939

**Comment by digitarald** [comment]
As it is very FxOS specific, I would rather track the platform feature [Implement W3C Manifest](https://bugzilla.mozilla.org/show_bug.cgi?id=997779).

**Comment by marco-c** [comment]
This should be closed now, shouldn't it?
