### ISSUE TITLE
Figure out what to do when chromestatus splits an API in different entries

### ISSUE THREAD

**Issue by marco-c** [mozilla/platatus#240]
chromestatus.com has five different entries for the Push API:
- Push API - https://www.chromestatus.com/features/5416033485586432
- Push API: Payloads - https://www.chromestatus.com/features/5746279325892608
- Push API: gcm_user_visible_only deprecation (removed) - https://www.chromestatus.com/feature/5778950739460096
- Push API: PushSubscription.subscriptionId - https://www.chromestatus.com/features/5283829761703936
- Web Notifications using Service Workers - https://www.chromestatus.com/feature/5480344312610816

I'd prefer a single entry for an API and call it supported when it's fully supported. Maybe we should make `chrome_ref` an array?

**Comment by TimAbraldes** [comment]
> Maybe we should make chrome_ref an array?

That sounds reasonable: It gives us more flexibility in terms of how we display API support.

**Comment by marco-c** [comment]
Duplicate of #278.
