### ISSUE TITLE
Add Web Speech Synthesis API to Firefox status

### ISSUE THREAD

**Issue by makotokato** [mozilla/platatus#243]
We will turn it on Firefox 45 Desktop.  So could you add this status?

Bugzilla ... https://bugzilla.mozilla.org/show_bug.cgi?id=1003439
MDN ... https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API
Spec .. https://dvcs.w3.org/hg/speech-api/raw-file/tip/webspeechapi.html
Edge status ... https://dev.windows.com/en-us/microsoft-edge/platform/status/webspeechapisynthesis
Chrome status ... shipped (http://www.chromestatus.com/features/4782875580825600)
Safari status ... shipped.

**Comment by marco-c** [comment]
Could you do it? We'd love feedback on the contribution process!
Creating a feature is really simple: https://github.com/mozilla/platatus/blob/master/CONTRIBUTING.md
You've already done most of the work (finding the status of other browsers, the spec and MDN URLs and the bugzilla tracking bug).
