### ISSUE TITLE
Shared Array Buffers bug is "NEW" and all the bugs it depends on are open, but we show it "Complete"

### ISSUE THREAD

**Issue by marco-c** [mozilla/platatus#249]
https://platatus.herokuapp.com/#shared_array_buffer
https://bugzilla.mozilla.org/show_bug.cgi?id=1225406

**Comment by marco-c** [comment]
Build on Heroku:
![platatus](https://cloud.githubusercontent.com/assets/1616846/12034291/360831ee-ae2f-11e5-8f6c-b12fd19ac2a7.png)

Local build:
![local_platatus](https://cloud.githubusercontent.com/assets/1616846/12034295/3e223a46-ae2f-11e5-81ea-65f9265fa020.png)

**Comment by brendandahl** [comment]
Your cache of the firefox version is probably out of date. Besides that we should update it to in-development since it's not shipping in 45

**Comment by marco-c** [comment]
I've removed the service worker from about:serviceworkers and cleared the cache, but I'm still seeing that.

**Comment by marco-c** [comment]
@brendandahl do you see the correct alternative on Heroku?

**Comment by brendandahl** [comment]
I see "Landed" locally and on heroku. By clearing the cache I mean removing files in dist/cache/*

**Comment by marco-c** [comment]
Ah, I thought we weren't showing "LANDED" for non-release versions, so I thought this was a problem on Heroku.
