### ISSUE TITLE
Define comprehensive list of features to track

### ISSUE THREAD

**Issue by dbialer** [mozilla/platatus#26]
Currently the list of features to track is not defined within this spec.  IE, Chrome, webkit all seem to track different things.  We should define out list relating to WADI (or do we wish to be comprehensive live IE?).

W3C Manifest
Service Workers 
Push API with permissions APIs
Notification Dashboard/Control
Push Service (autopush server supporting Webpush)
Offliner libraries (internal projects) oghliner and offliner
Background Sync (https://github.com/slightlyoff/BackgroundSync)

Some of these have subfeatures so that partial implementations may be tracked separately.  This issue is to come up with the canonical list to start.

**Comment by digitarald** [comment]
> Push Service (autopush server supporting Webpush)
> Offliner libraries (internal projects) oghliner and offliner

As these are not platform feature I would not merge them together with the rest to avoid confusion.

A good top list to start from would be https://www.chromestatus.com/features.json filtered down to the entries that have developer enthusiasm (field `web_dev_views.text`).

**Comment by digitarald** [comment]
The games team also wants to have their game specific APIs tracked. We need to find a middle ground from high level Web Audio to fine-grained `Math.imul()`

**Comment by digitarald** [comment]
Another source: https://developer.mozilla.org/en-US/docs/Web/Specification_list

**Comment by digitarald** [comment]
Now tracked in #68
