### ISSUE TITLE
Add OffscreenCanvas

### ISSUE THREAD

**Issue by Elchi3** [mozilla/platatus#279]
title: OffscreenCanvas
category: games
bugzilla: 1032848, 1172796, 801176
firefox_status: 44 (behind pref, gfx.offscreencanvas.enabled)
mdn_url: https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas
spec_url: https://wiki.whatwg.org/wiki/OffscreenCanvas

Allows canvas contexts (e.g. WebGL, Canvas2D) to be rendered in a worker / offscreen.

https://www.chromestatus.com/feature/5424182347169792

**Comment by marco-c** [comment]
Hello, can you try to open a pull request?
It should be very easy (https://github.com/mozilla/platatus/blob/master/CONTRIBUTING.md) and we'd love some feedback on the process.

**Comment by Elchi3** [comment]
Feedback:
* I thought I could use multiple bug numbers for displaying "x/y resolved".
* There is no `firefox_footnote` or a way to say that this is not active by default and not yet working on Windows.

**Comment by marco-c** [comment]
Thank you for the PR and for the feedback, really useful.

**Comment by ohenepee** [comment]
Hello! Newbie here... wasn't OffscreenCanvas supposed to show on [platform-status.mozilla.org/](https://platform-status.mozilla.org/) based on this PR or is there something I'm not getting, cos its bast 2 years now? And is there anyway to track when it'll land without being placed behind a flag?

**Comment by marco-c** [comment]
It was removed by https://github.com/mozilla/platform-status/pull/464.
