### ISSUE TITLE
Verify build output in a unit test (but generate the expected output list automatically)

### ISSUE THREAD

**Issue by potch** [mozilla/platatus#291]
I'm not sure what [this test](https://github.com/mozilla/platatus/blob/master/tests/nodeUnit.js#L39) is designed to ensure- it seems very brittle and likely to trip up potential contributors. It makes sense to either auto-generate the portion of the list driven by the features/ directory or to simply not have this test.

**Comment by marco-c** [comment]
For reference, https://github.com/mozilla/platatus/pull/265#discussion_r49603278.

**Comment by TimAbraldes** [comment]
As currently described, this issue was fixed by 84d9b9deb9d1916b7c1f0996ff6f36309788b96d

However, a day later we experienced #298. I'm morphing this issue to be about re-adding the test in a way that makes it less burdensome

**Comment by digitarald** [comment]
How would this test have caught the tabzilla issue?

**Comment by TimAbraldes** [comment]
I haven't looked into it, but from your comment in that issue:

> On first look, the tabzilla CSS doesn't seem to be included in the build output.

I inferred that we were missing a css file in our build output. Now that I'm looking a little closer, the tabzilla css maybe would have been part of bundle.css?

**Comment by digitarald** [comment]
Closing for now, maybe we can find better ways of ensuring not breaking the main page while checking expected files (like `status.json`).
