### ISSUE TITLE
tabzilla broken, shows as unformatted text

### ISSUE THREAD

**Issue by wfwalker** [mozilla/platatus#298]
When I visit platform-status.mozilla.org, I see the tabzilla as an unformatted piece of text.

<img width="585" alt="tabzilla-broken" src="https://cloud.githubusercontent.com/assets/812428/12628577/ae6ec83e-c4f8-11e5-8d03-b3b4d349402b.png">

**Comment by digitarald** [comment]
On first look, the tabzilla CSS doesn't seem to be included in the build output.

**Comment by digitarald** [comment]
Maybe caused by postcss update #294

**Comment by wfwalker** [comment]
could be related to fe4930189f7f05044c0b170bb21111174614597c ?

**Comment by TimAbraldes** [comment]
> On first look, the tabzilla CSS doesn't seem to be included in the build output.

If that's the case, this would have been caught by the test we removed in 84d9b9deb9d1916b7c1f0996ff6f36309788b96d

I'm morphing #291 to track us re-adding a less burdensome version of that test
