### ISSUE TITLE
Discuss: Information Architecture

### ISSUE THREAD

**Issue by digitarald** [mozilla/platatus#3]
Make a simple UI that serves both *casual browsing* and *experienced* users.

## Looking at prior art

- Long accordion list are hard for casual browsing as they require lots of browsing, clicking while hiding a big part of the list items
- Edge sees 20% of visitors coming from mobile

## Elements of a feature

- Title and one-line summary
- Firefox implementation status as first-level detail
- Enthusiasm/Implementation per vendor
  - States
    - *None*: Question mark - **Gray**
    - *Deprecated/Skepticism*: Disabled state - **Red**
    - *Under Consideration*: Logo enabled but faded - **Orange**
    - *In Development*: Nightly logo or another in-development indicator - **Yellow**
    - *Shipped*: Release logo - **Green**
  - Combination of color codes and logos
  - Additional links available to vendor status page and bug
- Standardization URL and stage
- Firefox meta (see [MVP](https://github.com/digitarald/platatus/wiki/MVP))
  - Bugzilla bug and status
  - Documentation
- Edit link to `features/*.md` file on github

## v1 Mockup

![Mobile Portrait Sketch](https://duct.io/platatus/mobile.png)

## v0 Drafts

Question: Which indicators for support status work best in a small space?

### Bars

![Bars](https://cloud.githubusercontent.com/assets/8599/10653405/33542a12-7814-11e5-804d-cf848eed5222.png)

### Circle indicators

![Circles](https://cloud.githubusercontent.com/assets/8599/10653404/33522c8a-7814-11e5-959f-97c686c37400.png)

**Comment by brendandahl** [comment]
Mapping other browser's statuses to ours:
https://public.etherpad-mozilla.org/p/browser-status

**Comment by brendandahl** [comment]
When filling in statuses in another bug 'none' doesn't seem to fit. 'no active development' seems more descriptive.

**Comment by digitarald** [comment]
## Idea 1 - Consensus bars
Bold visuals to easily read consensus. Hover the browser status bars expands them with additional details and labels:
<img width="1024" alt="2015-10-21 13 02 48" src="https://cloud.githubusercontent.com/assets/8599/10653405/33542a12-7814-11e5-804d-cf848eed5222.png">

## Idea 2
<img width="1024" alt="2015-10-21 09 40 46" src="https://cloud.githubusercontent.com/assets/8599/10653404/33522c8a-7814-11e5-959f-97c686c37400.png">
- Option 1 and 3 depend on short one-liner summaries - which should be our goal as developers can read more in the spec or docs. Another option is cutting the text after one line and letting the user expand it on click.
- Browser consensus again is easy to scan, either with icons (noisy?) or 2-character labels
- Additional links are tagged either below the summary or the browser statuses
- *Not done*
  - I wanted to give a prominent spot for bugzilla+bug-status and spec+spec-state
  - Firefox status could include additional details for prefixed and preffed-off

Any other information that we would need to show, maybe collapsed by default?

Lets just start prototyping on an interface and try out different combinations.

**Comment by delapuente** [comment]
Maybe we can take a look at the [Foxfooding application](https://foxfooding.github.io/) as its intention is quite aligned with platatus'.

**Comment by digitarald** [comment]
Can you elaborate, @delapuente? For the Foxfooding app, the audience are Firefox OS foxfooders (not web developers) and the content is a machup of various feeds for news and updates and issue tracker.

**Comment by delapuente** [comment]
It is not clear from `About` in the application but [in the message sent in dev-fxos mailing list](https://groups.google.com/d/msg/mozilla.dev.fxos/9eLoBZdcb20/6z5kcw1ICQAJ) you can read:

> You can expect the following going forward:
>   * News about the Foxfooding program, Firefox OS, and project happenings.
>   * Information about updates that we ship over-the-air to your foxfooding devices.
>   * Ongoing issues that we’re tackling, where we are in dealing with them, and guidance on how to get around them.
>   * Other assorted information, like interviews and press releases.

And Platatus is trying to fulfil similar goals, isn't it? News about Platatus itself to discover new features helping web developers, information about updates in the web technologies being implemented, ongoing issues with workarounds, polyfills, etc and links to related information...

I'm not saying to copy the look & feel from Foxfooding app but maybe we can keep an eye and try to deliver a similar UX. Does it make sense?

**Comment by digitarald** [comment]
*Changelog*: Added mockup from Sketch with various explorations.

**Comment by digitarald** [comment]
*Changelog* Updated mockup with new expanded view

**Comment by overholt** [comment]
I'm personally a fan of the vertical bars with colours for status and browser icons.
