### ISSUE TITLE
OffscreenCanvas is landed on Firefox 47 Nightly

### ISSUE THREAD

**Issue by kyoshino** [mozilla/platatus#304]
The 2D API is [now on Nightly](https://bugzilla.mozilla.org/show_bug.cgi?id=801176#c86).

**Comment by marco-c** [comment]
It's still disabled by default: http://hg.mozilla.org/mozilla-central/file/4ca883690e2a/modules/libpref/init/all.js#l4295

**Comment by marco-c** [comment]
Duplicate of #284.
