### ISSUE TITLE
platform status should include HTTP/2

### ISSUE THREAD

**Issue by wfwalker** [mozilla/platatus#305]
https://www.chromestatus.com/features/5152586365665280

**Comment by wfwalker** [comment]
https://bugzilla.mozilla.org/showdependencytree.cgi?id=1047594&hide_resolved=0

**Comment by wfwalker** [comment]
https://dev.windows.com/en-us/microsoft-edge/platform/status/http2?filter=f3f0000bf&search=http

**Comment by wfwalker** [comment]
https://http2.github.io/

**Comment by mykmelez** [comment]
http://caniuse.com/#feat=http2
