### ISSUE TITLE
Add functional tests

### ISSUE THREAD

**Issue by digitarald** [mozilla/platatus#31]
- Run on each build (Selenium)
- Downside: We don't have much interaction yet to test

@darkwing had recommendations using Intern and Selenium.

**Comment by darkwing** [comment]
Intern does unit testing as well, btw

**Comment by digitarald** [comment]
@TimAbraldes actually mentioned Intern when we talked about test frameworks in #8, so it makes sense to switch to one.

**Comment by digitarald** [comment]
Fixed by #37
