### ISSUE TITLE
Offline search doesn't work

### ISSUE THREAD

**Issue by digitarald** [mozilla/platatus#339]
offline-worker.js misses status.json which is needed for search.

I'm hesitant to include the `status.json` is 51kb (8kb gzipped). I want to see if an exported lunr search index is more compact.

**Comment by marco-c** [comment]
console.log('status.json length: ' + body.length);
console.log('index length: ' + JSON.stringify(searchIndex.toJSON()).length);

status.json length: 57720
index length: 66224
