### ISSUE TITLE
Firefox's First Run page makes all browser tests fail

### ISSUE THREAD

**Issue by zalun** [mozilla/platatus#379]
After updating the browser:
<img width="507" alt="screenshot 2016-03-22 14 25 34" src="https://cloud.githubusercontent.com/assets/97885/13953008/fd393f78-f039-11e5-9e32-0670afbdda87.png">
After a long wait (3 min)
```
0/59 tests failed
Listening on 0.0.0.0:9000
Tunnel started
Suite firefox on any platform FAILED
UnknownError: [POST http://localhost:4444/wd/hub/session / {"desiredCapabilities":{"browserName":"firefox","name":"tests/config/intern-browser","idle-timeout":60}}] Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
```
Full log: http://pastebin.com/yn6ccCrF

**Comment by brendandahl** [comment]
I was running into this in another project and did https://stackoverflow.com/questions/33937067/firefox-webdriver-opens-first-run-page-all-the-time
