### ISSUE TITLE
show status of tracked bugs, not status of tracker bug

### ISSUE THREAD

**Issue by wfwalker** [mozilla/platatus#51]
right now we are showing the status of tracker bugs, such as "bug (RESOLVED)".

IMHO the status of the tracker bug is rarely interesting. Instead, we should show a summary of the bugs tracked by the tracker, something like "bugs (26/30 RESOLVED)."

I have code like that at https://github.com/wfwalker/wadi-blessed-dashboard/blob/master/wadi.js#L40

**Comment by marco-c** [comment]
Fixed by #94.
