### ISSUE TITLE
[Discussion] What is platatus?

### ISSUE THREAD

**Issue by dbialer** [mozilla/platatus#6]
Discuss what is platatus?  What problem should it solve? Which technologies will be used and how?

**Comment by digitarald** [comment]
https://github.com/digitarald/platatus/wiki/MVP should answer the product questions.

**Comment by digitarald** [comment]
https://github.com/mozilla/wadi/issues/2 takes a shot at higher level what-is-success. Technologies are currently set in the repo (node/gulp/babel/etc) are to be extended as needed during v1 development.
