### ISSUE TITLE
Feature list v1

### ISSUE THREAD

**Issue by digitarald** [mozilla/platatus#68]
Follow up for https://github.com/mozilla/platatus/issues/26 , we will update this bug description as new ideas get added.

## Shortlist

- [x] W3C Manifest :package:
- [x] Service Workers :package:
- [x] Push API :package:
- [x] Streams API :package:
- [x] Fetch API :package:
- [x] Promises
- [x] Background Sync (https://github.com/slightlyoff/BackgroundSync)
- [x] asm.js :video_game:
- [x] wasm.js :video_game:
- [x] WebGL 1 :video_game:
- [x] WebGL 2 :video_game:
- [x] Web Audio :video_game:
- [x] Web Sockets :video_game:
- [x] WebRTC :video_game:
- [x] SIMD :video_game:
- [x] Page Visibility API :video_game: :package: 
- [x] Gamepad API :video_game:
- [x] Shared Array Buffers/Threading :video_game:
- [x] Fullscreen API :video_game: :package:
- [x] IndexedDB :video_game: :package:
- [x] Media Source Extensions (MSE)
- [x] Pointer Lock :video_game:
- [x] Screen Orientation API :video_game: 
- [x] Device Orientation/Motion Event :video_game: 
- [x] Vibration API :video_game: 
- [x] Custom Elements
- [x] Shadow DOM
- [x] HTML Templates
- [x] HTML Imports
- [x] Media Capture from Canvas
- [x] MediaRecorder
- [x] Permissions API

:video_game: - requested by games team
:package: - by app initiative
:exclamation: - piecemeal implementation/hard to track

## Backlog

- Web Cryptography API :exclamation:
- Presentation API :exclamation:
- ES6
  - Default parameters
  - Destructuring
  - new.target
  - Classes
  - Symbols
  - Unscopables
  - Proxies
- Pointer Events
- Ambient Light Sensor API
- Navigation Timing API
- Vibration API

**Comment by dbialer** [comment]
possibly ambient light sensor api http://www.w3.org/TR/ambient-light/

**Comment by digitarald** [comment]
Features with positive developer feedback from chrome:

- CSS filter() image function
- Geometry interfaces
- Media Capture from Canvas
- UIEvents Keyboard Events
- CSS font-display
- Credential Management API
- Debug API
- Frame Timing API
- HTMLCanvasElement.renderedPixelWidth/Height
- Local Font Access API
- Speech Recognition with WebRTC
- Standby API
- Accept-encoding: br on HTTPS connection
- Animated PNG
- Background Sync API
- CSS Scroll Snap Points
- CSS font-feature-settings
- CSS position: sticky
- Custom Web Notification timestamps
- Default parameters (ES6)
- Destructuring (ES6)
- Filters in 2D canvas
- HTTP Client Hints: Save-Data
- High Resolution Time Stamp for Events
- Interoperable body/documentElement scroll behavior
- MediaRecorder
- Permissions.request() and Permissions.revoke()
- Pointer Events
- Promise rejection tracking events
- Push API: Payloads
- Resource Hints - Preload
- Streams API
- Web NFC API
- WebAudio:  Add IIRFilterNode
- WebAudio: OfflineAudioContext.suspend() and resume()
- WebAudio: decodeAudioData returns a Promise
- beforescriptexecute and afterscriptexecute events
- inputmode
- stale-while-revalidate
- Array.prototype.includes
- UIEvent.sourceCapabilities & InputDeviceCapabilities.firesTouchEvents
- requestIdleCallback
- 'allow-popups-to-escape-sandbox' sandboxing flag.
- API to disable scroll restoration on history navigation
- Access relative orientation sensors from Chrome for Android for Virtual Reality
- Block modal dialogs inside a sandboxed iframe.
- HTTP Client Hints: DPR, Width, Viewport-Width
- Resource Hints - preconnect
- WebRTC Data Channel buffer monitoring with the "bufferedamountlow" event
- new.target (ES6)
- Audio Output Devices API
- CSS Motion Path
- Document's "first-party" takes ancestors into account.
- Subresource Integrity
- Document.scrollingElement
- Notification.data and ServiceWorkerRegistration.getNotifications()
- beforeinstallprompt event for web/native app install banners
- Allow JS-triggered copy/cut with a user gesture
- CSSOM Document.elementsFromPoint API
- Cache API (global scope)
- Permissions API
- Upgrade insecure requests
- WebAudio: Allow developers to close an AudioContext explicitly
- autocapitalize
- Classes (ES6)
- Fetch API
- Push API
- UI Events KeyboardEvent |code| attribute
- Web/native app install banners
- Blending of HTML and SVG elements
- ES6 numeric literals
- Cache API for Service Worker
- Content Security Policy Level 2
- Beacon
- Web Animations Javascript API [playback control]
- Web Application Manifest
- meta-theme-color
- <picture> Element
- Encoding API
- File constructor
- Screen Orientation API
- Symbols (ES6)
- Unscopables (ES6)
- <dialog> Element
- CSS "all" shorthand
- CSS Shapes Module Level 1
- Navigator.hardwareConcurrency 
- Subpixel font scaling
- CSS touch-action
- CSS will-change
- HTML Imports
- Object.observe()
- WOFF 2.0 (improved font compression)
- Web Animations JavaScript API [element.animate()] 
- CSS Blending of background images (mix-blend-mode)
- CSS Font Loading
- Prefixed Shadow DOM
- Scoped Styles
- Shadow DOM
- Unprefixed Web Audio API
- Custom Elements
- Opus in MSE and <video>
- Page Visibility API
- Web Speech API (synthesis)
- Animated WebP
- URL
- Vibration API
- DOM3 Wheel Events
- Device Motion
- CSS Device Adaptation
- Media Queries: resolution feature
- CSS Conditional Rules
- <template> Element
- CSS Gradients
- Web Speech API (input)
- requestAnimationFrame()
- Media Source Extensions
- Pointer Lock (Mouse Lock)
- Track element
- WebRTC
- CSS Flexbox
- Meta Referrer
- Mutation Observers
- Proxies (ES6)
- Touch Events
- Fullscreen API
- Quota Management API
- File System API (Chromium)
- Navigation Timing API
- Web SQL Database
- IndexedDB
- Form validation
- Runtime error reporting: ErrorEvent.
- WebP image format support
- matchMedia
- HTTP/2 (SPDY)
- HTTP Strict Transport Security (HSTS)
- Message Channels
- postMessage
- CSP 'manifest-src' rule for Web App Manifest
- Compositing and Blending in Canvas 2D
- ImageData constructor
- Parsing related_applications from Web Manifest
- MathML
- Subpixel precision for clientWidth, offsetWidth, scrollTop, et al

**Comment by dbialer** [comment]
a few others that come to mind:
requestautocomplete - https://bugzilla.mozilla.org/show_bug.cgi?id=1018291
Also some manifest related issues that may not have bugs filed yet - from fxos 2.6 backlog https://docs.google.com/presentation/d/1b6SBgBmI8AcANJGHT37b3Va6m1YNX6P5kEEcJg6lEgw/edit?usp=sharing:
Manifest property: theme_color
Manifest property: display - currently not fully supported
Manifest property: orientation
Manifest property: splash_screens
Manifest fetch
Manifest update
s a Gaia developer I want manifests to be fetched by the platform in order to be more compliant with the W3C web app manifest specification

**Comment by overholt** [comment]
A few random other things on Gecko's radar:

[Page transitions](http://chrislord.net/index.php/2015/04/24/web-navigation-transitions/)
&lt;link rel=prerender&gt; (aka prerendering)
[Media Session](https://mediasession.spec.whatwg.org/)
[FileSystem](http://w3c.github.io/filesystem-api/)
[Screen Orientation](https://w3c.github.io/screen-orientation/)
[Streams](https://streams.spec.whatwg.org/)
[IndexedDB Observables](https://github.com/dmurph/indexed-db-observers)
[Permissions API](https://w3c.github.io/permissions/)

**Comment by digitarald** [comment]
@overholt what is the browser consensus on `FileSystem`?

**Comment by digitarald** [comment]
@overholt also, what would be the platform take on tracking stale feature development like requestautocomplete?

**Comment by overholt** [comment]
FileSystem is seen favourably AFAIK but that's perhaps not fair as it's not yet ready for much comment.
Stale features are still worth tracking IMO as long as it's not too much work.

**Comment by marco-c** [comment]
Chrome has different entries for "Permissions API" and "Permissions.request() and Permissions.revoke()". What should we do?

**Comment by overholt** [comment]
We should probably split them out, too, given the split we've got in https://bugzilla.mozilla.org/show_bug.cgi?id=1105827 (.query being done now and .request/.revoke being done later) and this discussion on dev-platform: https://groups.google.com/d/msg/mozilla.dev.platform/7RnCrXoXdG4/Oy84atEoKgAJ

**Comment by digitarald** [comment]
Let's simplify for v1 and just add Permissions API, leaveing the 2-tiered hierarchy for v2.

**Comment by marco-c** [comment]
Filed #127.

**Comment by digitarald** [comment]
We are close to 100% of the shortlist - @overholt, would you help checking high-level consistency of the data so far on https://mozilla.github.io/platatus/ and if it reflects Mozilla properly (not so much others)?

**Comment by overholt** [comment]
A few comments:

- Custom Elements is "shipped" by Chrome but the spec will change before it becomes real
- "... the process that binds them; fetching." <- the ; should be a :
- we're not going to ship HTML Imports (see https://hacks.mozilla.org/2014/12/mozilla-and-web-components/)
- IE's supposedly shipping a prefixed Streams and not the new spec but we say they are shipping

Otherwise, looks great!

**Comment by digitarald** [comment]
All addressed in #137, except *Custom Elements* and *IE Streams* as that is data coming from external sources. We could override the status on our side or allow adding footnotes?

**Comment by overholt** [comment]
Footnotes may be worth it since it looks like they're shipping things that we're not but there's more nuance here.

**Comment by digitarald** [comment]
done for v1, backlog should guide us to file more features
