### ISSUE TITLE
Design tweaks

### ISSUE THREAD

**Issue by digitarald** [mozilla/platatus#72]
The initial layout is launched, here come the tweaks :hammer: …

- [x] Tone down colors (green especially) to be less neon :zap:
- [x] Full browser logos on mobile
- [x] Better bugzilla label (`NEW` to `12/24 Resolved`, normalize the rest)
- [x] Anchor for feature (see gh headers)
- [x] Better separation (more space?)
- [x] Status click targets for desktop

**Comment by overholt** [comment]
Are the browser icons supposed to be fully visible on desktop? I only see the top halves on desktop but the full images when I look using responsive design mode with a small display size.

**Comment by digitarald** [comment]
@overholt the half-size is expected, but I'll either make sure it does look intended or switch to a design with full icon.
