### ISSUE TITLE
Differentiate experiment/prefixed/shipped?

### ISSUE THREAD

**Issue by marco-c** [mozilla/platatus#73]
For example, WebGL is prefixed in IE (see https://dev.windows.com/en-us/microsoft-edge/platform/status/webglcanvas3d), but we say it is shipped. Should we differentiate between the two?

**Comment by digitarald** [comment]
v2, we get those details only from chrome and ie.

Also prefixing is a thing of the past and we shouldn't see it for future features, so this would only affect "older" entries.

**Comment by digitarald** [comment]
Caniuse provides these details, so I am taking this off the table for now. Anything that doesn't ship in release by default (preffed off and experimental framework should be marked in-development.
